<?php

return [
    'QUIZ_ALLOW_DELAY' => env('QUIZ_ALLOW_DELAY', false),
    'QUIZ_MAX_DELAY' => env('QUIZ_MAX_DELAY', 25),
    'QUESTION_MAX_DURATION' => env('QUESTION_MAX_DURATION', 25),
    'QUESTION_DEFAULT_DURATION' => env('QUESTION_DEFAULT_DURATION', 20),
];
